gabaritos = {
    "021": {
        "programa_1": [
            { "questao": 1, "cor": "Verde", "resposta": "alimentos" },
            { "questao": 2, "cor": "Vermelho", "resposta": "fast food" },
            { "questao": 3, "cor": "Vermelho", "resposta": "energia" },
            { "questao": 4, "cor": "Vermelho", "resposta": "refrigerante" },
            { "questao": 5, "cor": "Azul", "resposta": "carro" },
            { "questao": 6, "cor": "Verde", "resposta": "Sonic" },
            { "questao": 7, "cor": "Azul", "resposta": "fugir" },
            { "questao": 8, "cor": "Vermelho", "resposta": "saltar" },
            { "questao": 9, "cor": "Vermelho", "resposta": "amigo" },
            { "questao": 10, "cor": "Azul", "resposta": "respirar" },
            { "questao": 11, "cor": "Verde", "resposta": "mergulhar" },
            { "questao": 12, "cor": "Amarelo", "resposta": "porquinho" },
            { "questao": 13, "cor": "Azul", "resposta": "circular" },
            { "questao": 14, "cor": "Verde", "resposta": "pneu" },
            { "questao": 15, "cor": "Verde", "resposta": "velocidade" },
            { "questao": 16, "cor": "Amarelo", "resposta": "acelerador" },
            { "questao": 17, "cor": "Verde", "resposta": "forma" },
            { "questao": 18, "cor": "Verde", "resposta": "guepardo" },
            { "questao": 19, "cor": "Amarelo", "resposta": "pião" },
            { "questao": 20, "cor": "Verde", "resposta": "luz" },
            { "questao": 21, "cor": "Vermelho", "resposta": "iluminado" },
            { "questao": 22, "cor": "Azul", "resposta": "sombra" },
            { "questao": 23, "cor": "Vermelho", "resposta": "escuro" },
            { "questao": 24, "cor": "Azul", "resposta": "contrário" },
            { "questao": 25, "cor": "Vermelho", "resposta": "sombra do Sonic" },
            { "questao": 26, "cor": "Vermelho", "resposta": "lâmpada" },
            { "questao": 27, "cor": "Vermelho", "resposta": "A" },
            { "questao": 28, "cor": "Amarelo", "resposta": "B" },
            { "questao": 29, "cor": "Azul", "resposta": "C" },
            { "questao": 30, "cor": "Verde", "resposta": "D" },
        ],
        "programa_2": [
            { "questao": 31, "cor": "Azul", "resposta": "computador" },
            { "questao": 32, "cor": "Verde", "resposta": "Sonic" },
            { "questao": 33, "cor": "Vermelho", "resposta": "funil" },
            { "questao": 34, "cor": "Amarelo", "resposta": "ímã" },
            { "questao": 35, "cor": "Vermelho", "resposta": "tomada" },
            { "questao": 36, "cor": "Verde", "resposta": "chama" },
            { "questao": 37, "cor": "Amarelo", "resposta": "giz" },
            { "questao": 38, "cor": "Verde", "resposta": "tubo de ensaio" },
            { "questao": 39, "cor": "Azul", "resposta": "ímã" },
            { "questao": 40, "cor": "Amarelo", "resposta": "metal" },
            { "questao": 41, "cor": "Azul", "resposta": "metal" },
            { "questao": 42, "cor": "Azul", "resposta": "pólos" },
            { "questao": 43, "cor": "Amarelo", "resposta": "bússola" },
            { "questao": 44, "cor": "Verde", "resposta": "orientar" },
            { "questao": 45, "cor": "Verde", "resposta": "D (Ótica)" },
            { "questao": 46, "cor": "Amarelo", "resposta": "F (Magnetismo)" },
            { "questao": 47, "cor": "Vermelho", "resposta": "E (Eletricidade)" },
            { "questao": 48, "cor": "Azul", "resposta": "A (Acústica)" },
            { "questao": 49, "cor": "Amarelo", "resposta": "B (Mecânica)" },
            { "questao": 50, "cor": "Verde", "resposta": "C (Termodinâmica)" },
            { "questao": 51, "cor": "Verde", "resposta": "ESMERALDA" },
            { "questao": 52, "cor": "Amarelo", "resposta": "TOPÁZIO" },
            { "questao": 53, "cor": "Vermelho", "resposta": "RUBI" },
            { "questao": 54, "cor": "Azul", "resposta": "TURQUESA" },
            { "questao": 55, "cor": "Azul", "resposta": "AMETISTA" },
            { "questao": 56, "cor": "Verde", "resposta": "DIAMANTE" },
            { "questao": 57, "cor": "Amarelo", "resposta": "TOPÁZIO" },
            { "questao": 58, "cor": "Azul", "resposta": "ÁGUA MARINHA" },
            { "questao": 59, "cor": "Vermelho", "resposta": "RUBI" },
            { "questao": 60, "cor": "Azul", "resposta": "cinza" },
        ],
        "programa_3": [
            { "questao": 61, "cor": "Amarelo", "resposta": "pássaro" },
            { "questao": 62, "cor": "Vermelho", "resposta": "despertador" },
            { "questao": 63, "cor": "Azul", "resposta": "trompete" },
            { "questao": 64, "cor": "Vermelho", "resposta": "som forte" },
            { "questao": 65, "cor": "Amarelo", "resposta": "som forte" },
            { "questao": 66, "cor": "Verde", "resposta": "som forte" },
            { "questao": 67, "cor": "Verde", "resposta": "quentes" },
            { "questao": 68, "cor": "Verde", "resposta": "calor" },
            { "questao": 69, "cor": "Azul", "resposta": "esquentar" },
            { "questao": 70, "cor": "Amarelo", "resposta": "bom" },
            { "questao": 71, "cor": "Verde", "resposta": "derreter" },
            { "questao": 72, "cor": "Verde", "resposta": "madeira" },
            { "questao": 73, "cor": "Vermelho", "resposta": "mau" },
            { "questao": 74, "cor": "Azul", "resposta": "Sonic" },
            { "questao": 75, "cor": "Vermelho", "resposta": "caracol" },
            { "questao": 76, "cor": "Amarelo", "resposta": "foguete" },
            { "questao": 77, "cor": "Vermelho", "resposta": "pena" },
            { "questao": 78, "cor": "Verde", "resposta": "elefante" },
            { "questao": 79, "cor": "Amarelo", "resposta": "Sol" },
            { "questao": 80, "cor": "Vermelho", "resposta": "gelo" },
            { "questao": 81, "cor": "Azul", "resposta": "chocolate" },
            { "questao": 82, "cor": "Vermelho", "resposta": "fornecem" },
            { "questao": 83, "cor": "Verde", "resposta": "Sonic" },
            { "questao": 84, "cor": "Verde", "resposta": "hot dog" },
            { "questao": 85, "cor": "Amarelo", "resposta": "doces" },
            { "questao": 86, "cor": "Azul", "resposta": "fritas" },
            { "questao": 87, "cor": "Azul", "resposta": "C" },
            { "questao": 88, "cor": "Vermelho", "resposta": "A" },
            { "questao": 89, "cor": "Verde", "resposta": "D" },
            { "questao": 90, "cor": "Amarelo", "resposta": "B" },
        ],
        "programa_4": [
            { "questao": 91, "cor": "Amarelo", "resposta": "olhos" },
            { "questao": 92, "cor": "Vermelho", "resposta": "mão" },
            { "questao": 93, "cor": "Verde", "resposta": "cheiro" },
            { "questao": 94, "cor": "Azul", "resposta": "nariz" },
            { "questao": 95, "cor": "Amarelo", "resposta": "língua" },
            { "questao": 96, "cor": "Azul", "resposta": "ouvidos" },
            { "questao": 97, "cor": "Verde", "resposta": "pele" },
            { "questao": 98, "cor": "Amarelo", "resposta": "B" },
            { "questao": 99, "cor": "Azul", "resposta": "C" },
            { "questao": 100, "cor": "Vermelho", "resposta": "A" },
            { "questao": 101, "cor": "Verde", "resposta": "F" },
            { "questao": 102, "cor": "Vermelho", "resposta": "E" },
            { "questao": 103, "cor": "Azul", "resposta": "D" },
            { "questao": 104, "cor": "Vermelho", "resposta": "esquenta" },
            { "questao": 105, "cor": "Verde", "resposta": "ferve" },
            { "questao": 106, "cor": "Azul", "resposta": "vapor" },
            { "questao": 107, "cor": "Amarelo", "resposta": "congela" },
            { "questao": 108, "cor": "Vermelho", "resposta": "gelo" },
            { "questao": 109, "cor": "Amarelo", "resposta": "derrete" },
            { "questao": 110, "cor": "Azul", "resposta": "água" },
            { "questao": 111, "cor": "Amarelo", "resposta": "emagreceu" },
            { "questao": 112, "cor": "Azul", "resposta": "esvaziou" },
            { "questao": 113, "cor": "Azul", "resposta": "magro" },
            { "questao": 114, "cor": "Amarelo", "resposta": "parar" },
            { "questao": 115, "cor": "Vermelho", "resposta": "pouco" },
            { "questao": 116, "cor": "Azul", "resposta": "descer" },
            { "questao": 117, "cor": "Azul", "resposta": "planetas" },
            { "questao": 118, "cor": "Verde", "resposta": "Terra" },
            { "questao": 119, "cor": "Vermelho", "resposta": "Lua" },
            { "questao": 120, "cor": "Verde", "resposta": "Saturno" },
        ],
        "programa_5": [
            { "questao": 121, "cor": "Azul", "resposta": "Sol" },
            { "questao": 122, "cor": "Azul", "resposta": "Gelo" },
            { "questao": 123, "cor": "Amarelo", "resposta": "Pinguim" },
            { "questao": 124, "cor": "Verde", "resposta": "Abacaxi" },
            { "questao": 125, "cor": "Vermelho", "resposta": "Papagaio" },
            { "questao": 126, "cor": "Vermelho", "resposta": "Alho" },
            { "questao": 127, "cor": "Azul", "resposta": "Banana (Buzz Bomber)" },
            { "questao": 128, "cor": "Verde", "resposta": "Jacaré (Jaws)" },
            { "questao": 129, "cor": "Amarelo", "resposta": "Minhoca (Moto Bug)" },
            { "questao": 130, "cor": "Amarelo", "resposta": "Cavalo (Caterkiller)" },
            { "questao": 131, "cor": "Verde", "resposta": "Régua (Roller)" },
            { "questao": 132, "cor": "Verde", "resposta": "Sapato (Spikes)" },
            { "questao": 133, "cor": "Amarelo", "resposta": "Nuvem (Newtron)" },
            { "questao": 134, "cor": "Vermelho", "resposta": "Máquina" },
            { "questao": 135, "cor": "Amarelo", "resposta": "Máquina" },
            { "questao": 136, "cor": "Azul", "resposta": "Máquina" },
            { "questao": 137, "cor": "Verde", "resposta": "Máquina" },
            { "questao": 138, "cor": "Vermelho", "resposta": "Máquina" },
            { "questao": 139, "cor": "Azul", "resposta": "Máquina" },
            { "questao": 140, "cor": "Verde", "resposta": "Máquina" },
            { "questao": 141, "cor": "Verde", "resposta": "D" },
            { "questao": 142, "cor": "Amarelo", "resposta": "E" },
            { "questao": 143, "cor": "Vermelho", "resposta": "A" },
            { "questao": 144, "cor": "Azul", "resposta": "F" },
            { "questao": 145, "cor": "Amarelo", "resposta": "B" },
            { "questao": 146, "cor": "Verde", "resposta": "C" },
            { "questao": 147, "cor": "Vermelho", "resposta": "1, 6, 10, 14 (Sally)" },
            { "questao": 148, "cor": "Amarelo", "resposta": "5, 4, 9, 16 (Chirps)" },
            { "questao": 149, "cor": "Vermelho", "resposta": "9, 2, 5, 16 (Tux)" },
            { "questao": 150, "cor": "Amarelo", "resposta": "13, 2, 7, 12 (Joe Sushi)" },
        ],
    },
    "081": {
        "programa_1": [
            { "questao": 1, "cor": "Verde", "resposta": "équidna" },
            { "questao": 2, "cor": "Vermelho", "resposta": "espinhos" },
            { "questao": 3, "cor": "Vermelho", "resposta": "comprida e fina" },
            { "questao": 4, "cor": "Verde", "resposta": "unhas" },
            { "questao": 5, "cor": "Verde", "resposta": "escavar buracos na terra" },
            { "questao": 6, "cor": "Amarelo", "resposta": "4 patas" },
            { "questao": 7, "cor": "Amarelo", "resposta": "2 minutos" },
            { "questao": 8, "cor": "Azul", "resposta": "baleia azul" },
            { "questao": 9, "cor": "Vermelho", "resposta": "peixe-boi" },
            { "questao": 10, "cor": "Verde", "resposta": "guepardo" },
            { "questao": 11, "cor": "Amarelo", "resposta": "preguiça-de-três-dedos" },
            { "questao": 12, "cor": "Vermelho", "resposta": "60 km/h" },
            { "questao": 13, "cor": "Vermelho", "resposta": "54 metros por hora" },
            { "questao": 14, "cor": "Verde", "resposta": "710" },
            { "questao": 15, "cor": "Azul", "resposta": "250 milhões" },
            { "questao": 16, "cor": "Amarelo", "resposta": "gorila" },
            { "questao": 17, "cor": "Vermelho", "resposta": "urso de Kodiak" },
            { "questao": 18, "cor": "Amarelo", "resposta": "morcego" },
            { "questao": 19, "cor": "Verde", "resposta": "capivara" },
            { "questao": 20, "cor": "Vermelho", "resposta": "cão fila" },
            { "questao": 21, "cor": "Azul", "resposta": "tiranossauro Rex" },
            { "questao": 22, "cor": "Vermelho", "resposta": "75 milhões de anos" },
            { "questao": 23, "cor": "Azul", "resposta": "100 toneladas" },
            { "questao": 24, "cor": "Azul", "resposta": "1,36 m x 81 cm" },
            { "questao": 25, "cor": "Amarelo", "resposta": "70 gramas" },
            { "questao": 26, "cor": "Verde", "resposta": "régua" },
            { "questao": 27, "cor": "Vermelho", "resposta": "pterossauro" },
            { "questao": 28, "cor": "Amarelo", "resposta": "12 metros" },
            { "questao": 29, "cor": "Vermelho", "resposta": "répteis" },
            { "questao": 30, "cor": "Amarelo", "resposta": "lagarto" },
        ],
        "programa_2": [
            { "questao": 31, "cor": "Verde", "resposta": "Groenlândia" },
            { "questao": 32, "cor": "Vermelho", "resposta": "Bananal" },
            { "questao": 33, "cor": "Azul", "resposta": "Fernando de Noronha" },
            { "questao": 34, "cor": "Vermelho", "resposta": "um conjunto de ilhas" },
            { "questao": 35, "cor": "Azul", "resposta": "acidentes geográficos" },
            { "questao": 36, "cor": "Azul", "resposta": "que bóia" },
            { "questao": 37, "cor": "Amarelo", "resposta": "minerais" },
            { "questao": 38, "cor": "Verde", "resposta": "Brasil" },
            { "questao": 39, "cor": "Verde", "resposta": "diamante" },
            { "questao": 40, "cor": "Verde", "resposta": "gema" },
            { "questao": 41, "cor": "Amarelo", "resposta": "dura" },
            { "questao": 42, "cor": "Verde", "resposta": "vidro" },
            { "questao": 43, "cor": "Vermelho", "resposta": "Via Láctea" },
            { "questao": 44, "cor": "Azul", "resposta": "Júpiter" },
            { "questao": 45, "cor": "Vermelho", "resposta": "Sirius" },
            { "questao": 46, "cor": "Verde", "resposta": "Sol" },
            { "questao": 47, "cor": "Vermelho", "resposta": "Plutão" },
            { "questao": 48, "cor": "Verde", "resposta": "Vênus" },
            { "questao": 49, "cor": "Amarelo", "resposta": "Saturno" },
            { "questao": 50, "cor": "Azul", "resposta": "Saturno" },
            { "questao": 51, "cor": "Amarelo", "resposta": "Equador" },
            { "questao": 52, "cor": "Azul", "resposta": "Amazonas" },
            { "questao": 53, "cor": "Vermelho", "resposta": "Saara" },
            { "questao": 54, "cor": "Vermelho", "resposta": "México" },
            { "questao": 55, "cor": "Amarelo", "resposta": "Pacífico" },
            { "questao": 56, "cor": "Vermelho", "resposta": "Everest" },
            { "questao": 57, "cor": "Amarelo", "resposta": "TITÃS" },
            { "questao": 58, "cor": "Amarelo", "resposta": "DAVI" },
            { "questao": 59, "cor": "Amarelo", "resposta": "SEQUÓIAS" },
            { "questao": 60, "cor": "Amarelo", "resposta": "2,31 m" },
        ],
        "programa_3": [
            { "questao": 61, "cor": "Azul", "resposta": "morangos" },
            { "questao": 62, "cor": "Verde", "resposta": "Austrália" },
            { "questao": 63, "cor": "Azul", "resposta": "Wisconsin" },
            { "questao": 64, "cor": "Verde", "resposta": "ovos" },
            { "questao": 65, "cor": "Verde", "resposta": "1988" },
            { "questao": 66, "cor": "Verde", "resposta": "1.000" },
            { "questao": 67, "cor": "Vermelho", "resposta": "quarto" },
            { "questao": 68, "cor": "Azul", "resposta": "52" },
            { "questao": 69, "cor": "Vermelho", "resposta": "Romário" },
            { "questao": 70, "cor": "Vermelho", "resposta": "94" },
            { "questao": 71, "cor": "Amarelo", "resposta": "Brasil" },
            { "questao": 72, "cor": "Azul", "resposta": "162" },
            { "questao": 73, "cor": "Vermelho", "resposta": "C (2,45m)" },
            { "questao": 74, "cor": "Vermelho", "resposta": "A (23,12m)" },
            { "questao": 75, "cor": "Amarelo", "resposta": "E (8,95m)" },
            { "questao": 76, "cor": "Amarelo", "resposta": "F (95,66m)" },
            { "questao": 77, "cor": "Amarelo", "resposta": "D (6,14m)" },
            { "questao": 78, "cor": "Verde", "resposta": "H (74,08m)" },
            { "questao": 79, "cor": "Verde", "resposta": "B (86,74m)" },
            { "questao": 80, "cor": "Azul", "resposta": "G (17,97m)" },
            { "questao": 81, "cor": "Azul", "resposta": "chuchu" },
            { "questao": 82, "cor": "Amarelo", "resposta": "concerto" },
            { "questao": 83, "cor": "Vermelho", "resposta": "assinar" },
            { "questao": 84, "cor": "Verde", "resposta": "exceção" },
            { "questao": 85, "cor": "Amarelo", "resposta": "açúcar" },
            { "questao": 86, "cor": "Vermelho", "resposta": "xícara" },
            { "questao": 87, "cor": "Verde", "resposta": "BANDO" },
            { "questao": 88, "cor": "Amarelo", "resposta": "CARDUME" },
            { "questao": 89, "cor": "Amarelo", "resposta": "CONSTELAÇÃO" },
            { "questao": 90, "cor": "Verde", "resposta": "ALCATÉIA" },
        ],
        "programa_4": [
            { "questao": 91, "cor": "Amarelo", "resposta": "recente" },
            { "questao": 92, "cor": "Verde", "resposta": "dons" },
            { "questao": 93, "cor": "Azul", "resposta": "origem" },
            { "questao": 94, "cor": "Amarelo", "resposta": "aniquilado" },
            { "questao": 95, "cor": "Vermelho", "resposta": "demente" },
            { "questao": 96, "cor": "Verde", "resposta": "boiar" },
            { "questao": 97, "cor": "Amarelo", "resposta": "NEVE" },
            { "questao": 98, "cor": "Vermelho", "resposta": "FERVENTE" },
            { "questao": 99, "cor": "Verde", "resposta": "ZELÂNDIA" },
            { "questao": 100, "cor": "Amarelo", "resposta": "RICHTER" },
            { "questao": 101, "cor": "Amarelo", "resposta": "MAUNA LOA" },
            { "questao": 102, "cor": "Verde", "resposta": "LAVA" },
            { "questao": 103, "cor": "Azul", "resposta": "FOGO" },
            { "questao": 104, "cor": "Vermelho", "resposta": "C (China)" },
            { "questao": 105, "cor": "Vermelho", "resposta": "D (São Paulo)" },
            { "questao": 106, "cor": "Vermelho", "resposta": "G (Estados Unidos)" },
            { "questao": 107, "cor": "Azul", "resposta": "B (Rio de Janeiro)" },
            { "questao": 108, "cor": "Verde", "resposta": "F (Orlando)" },
            { "questao": 109, "cor": "Vermelho", "resposta": "A (Egito)" },
            { "questao": 110, "cor": "Azul", "resposta": "E (Japão)" },
            { "questao": 111, "cor": "Azul", "resposta": "Neil Armstrong" },
            { "questao": 112, "cor": "Azul", "resposta": "Amir Klink" },
            { "questao": 113, "cor": "Verde", "resposta": "Alemanha" },
            { "questao": 114, "cor": "Verde", "resposta": "515,3" },
            { "questao": 115, "cor": "Azul", "resposta": "Moscou" },
            { "questao": 116, "cor": "Azul", "resposta": "ultrapassam" },
            { "questao": 117, "cor": "Vermelho", "resposta": "B (Esmeralda)" },
            { "questao": 118, "cor": "Azul", "resposta": "D (Nave)" },
            { "questao": 119, "cor": "Vermelho", "resposta": "C (Uvas)" },
            { "questao": 120, "cor": "Azul", "resposta": "A (Helicóptero)" },
        ],
        "programa_5": [
            { "questao": 121, "cor": "Verde", "resposta": "O Parque dos Dinossauros" },
            { "questao": 122, "cor": "Verde", "resposta": "Batman" },
            { "questao": 123, "cor": "Amarelo", "resposta": "Esqueceram de Mim" },
            { "questao": 124, "cor": "Azul", "resposta": "Conde Drácula" },
            { "questao": 125, "cor": "Verde", "resposta": "Universal City" },
            { "questao": 126, "cor": "Azul", "resposta": "1975" },
            { "questao": 127, "cor": "Amarelo", "resposta": "C (Hidrogênio)" },
            { "questao": 128, "cor": "Amarelo", "resposta": "D (Ferro)" },
            { "questao": 129, "cor": "Verde", "resposta": "F (Itaipu)" },
            { "questao": 130, "cor": "Vermelho", "resposta": "B (Fukushima)" },
            { "questao": 131, "cor": "Azul", "resposta": "A (IBM)" },
            { "questao": 132, "cor": "Amarelo", "resposta": "G (Harper Lake Site)" },
            { "questao": 133, "cor": "Vermelho", "resposta": "E (Radônio)" },
            { "questao": 134, "cor": "Amarelo", "resposta": "Atlântida" },
            { "questao": 135, "cor": "Azul", "resposta": "Eufrates" },
            { "questao": 136, "cor": "Vermelho", "resposta": "Creta" },
            { "questao": 137, "cor": "Amarelo", "resposta": "navegadores" },
            { "questao": 138, "cor": "Verde", "resposta": "México" },
            { "questao": 139, "cor": "Verde", "resposta": "Macedônia" },
            { "questao": 140, "cor": "Verde", "resposta": "Jerusalém" },
            { "questao": 141, "cor": "Verde", "resposta": "D (Entrada da Caverna)" },
            { "questao": 142, "cor": "Vermelho", "resposta": "E (Pé de trás)" },
            { "questao": 143, "cor": "Amarelo", "resposta": "B (Topo do Vulcão)" },
            { "questao": 144, "cor": "Vermelho", "resposta": "F (Pé da frente)" },
            { "questao": 145, "cor": "Vermelho", "resposta": "A (Céu e Montanha)" },
            { "questao": 146, "cor": "Vermelho", "resposta": "C (Braço e Cabelo)" },
            { "questao": 147, "cor": "Vermelho", "resposta": "1, 6, 11, 16" },
            { "questao": 148, "cor": "Azul", "resposta": "5, 14, 15, 12" },
            { "questao": 149, "cor": "Azul", "resposta": "9, 10, 7, 8" },
            { "questao": 150, "cor": "Amarelo", "resposta": "13, 2, 3, 4" },
        ],
    },
    "131": {
        "programa_1": [
            { "questao": 1, "cor": "Amarelo", "resposta": "porco-espinho" },
            { "questao": 2, "cor": "Vermelho", "resposta": "Ataque Giratório Supersônico" },
            { "questao": 3, "cor": "Azul", "resposta": "azuis" },
            { "questao": 4, "cor": "Verde", "resposta": "vermelhas" },
            { "questao": 5, "cor": "Verde", "resposta": "cientista / laboratório" },
            { "questao": 6, "cor": "Amarelo", "resposta": "Dr. Ivo Robotnik" },
            { "questao": 7, "cor": "Vermelho", "resposta": "rabos" },
            { "questao": 8, "cor": "Azul", "resposta": "helicóptero" },
            { "questao": 9, "cor": "Amarelo", "resposta": "balão" },
            { "questao": 10, "cor": "Verde", "resposta": "mais" },
            { "questao": 11, "cor": "Amarelo", "resposta": "foguete" },
            { "questao": 12, "cor": "Verde", "resposta": "leves" },
            { "questao": 13, "cor": "Vermelho", "resposta": "trem-bala" },
            { "questao": 14, "cor": "Vermelho", "resposta": "guepardo" },
            { "questao": 15, "cor": "Azul", "resposta": "peixe-voador" },
            { "questao": 16, "cor": "Azul", "resposta": "águia" },
            { "questao": 17, "cor": "Vermelho", "resposta": "ultrapassam" },
            { "questao": 18, "cor": "Azul", "resposta": "mais" },
            { "questao": 19, "cor": "Azul", "resposta": "velocidade" },
            { "questao": 20, "cor": "Amarelo", "resposta": "rápido" },
            { "questao": 21, "cor": "Vermelho", "resposta": "invisíveis" },
            { "questao": 22, "cor": "Vermelho", "resposta": "devagar" },
            { "questao": 23, "cor": "Amarelo", "resposta": "peludos" },
            { "questao": 24, "cor": "Vermelho", "resposta": "depressa" },
            { "questao": 25, "cor": "Amarelo", "resposta": "helicóptero" },
            { "questao": 26, "cor": "Verde", "resposta": "liquidificador" },
            { "questao": 27, "cor": "Vermelho", "resposta": "ventilador" },
            { "questao": 28, "cor": "Azul", "resposta": "hélice" },
            { "questao": 29, "cor": "Vermelho", "resposta": "cata-vento" },
            { "questao": 30, "cor": "Azul", "resposta": "moinho" },
        ],
        "programa_2": [
            { "questao": 31, "cor": "Azul", "resposta": "1,2,6,8,9,13,14" },
            { "questao": 32, "cor": "Amarelo", "resposta": "1,2,3,7,12,16" },
            { "questao": 33, "cor": "Vermelho", "resposta": "Sonic está correndo com Tails" },
            { "questao": 34, "cor": "Verde", "resposta": "5,9,13,11,14,7" },
            { "questao": 35, "cor": "Azul", "resposta": "4,15,1,10,2,9" },
            { "questao": 36, "cor": "Vermelho", "resposta": "1,16,11,5,3" },
            { "questao": 37, "cor": "Verde", "resposta": "mais" },
            { "questao": 38, "cor": "Vermelho", "resposta": "descansar" },
            { "questao": 39, "cor": "Amarelo", "resposta": "tartaruga" },
            { "questao": 40, "cor": "Vermelho", "resposta": "lento" },
            { "questao": 41, "cor": "Azul", "resposta": "longe" },
            { "questao": 42, "cor": "Verde", "resposta": "desistiu" },
            { "questao": 43, "cor": "Vermelho", "resposta": "competir" },
            { "questao": 44, "cor": "Azul", "resposta": "vencer" },
            { "questao": 45, "cor": "Verde", "resposta": "F" },
            { "questao": 46, "cor": "Vermelho", "resposta": "A" },
            { "questao": 47, "cor": "Amarelo", "resposta": "B" },
            { "questao": 48, "cor": "Azul", "resposta": "D" },
            { "questao": 49, "cor": "Verde", "resposta": "C" },
            { "questao": 50, "cor": "Vermelho", "resposta": "E" },
            { "questao": 51, "cor": "Vermelho", "resposta": "B" },
            { "questao": 52, "cor": "Azul", "resposta": "E" },
            { "questao": 53, "cor": "Vermelho", "resposta": "A" },
            { "questao": 54, "cor": "Verde", "resposta": "D" },
            { "questao": 55, "cor": "Azul", "resposta": "C" },
            { "questao": 56, "cor": "Amarelo", "resposta": "F" },
            { "questao": 57, "cor": "Verde", "resposta": "SONIC" },
            { "questao": 58, "cor": "Azul", "resposta": "GOSTA" },
            { "questao": 59, "cor": "Verde", "resposta": "DE" },
            { "questao": 60, "cor": "Verde", "resposta": "CORRER" },
        ],
        "programa_3": [
            { "questao": 61, "cor": "Verde", "resposta": "foguete" },
            { "questao": 62, "cor": "Vermelho", "resposta": "carro F1" },
            { "questao": 63, "cor": "Azul", "resposta": "guepardo" },
            { "questao": 64, "cor": "Vermelho", "resposta": "tubarão" },
            { "questao": 65, "cor": "Vermelho", "resposta": "trem-bala" },
            { "questao": 66, "cor": "Amarelo", "resposta": "águia" },
            { "questao": 67, "cor": "Azul", "resposta": "Os pés de Sonic giram como rodas." },
            {
      "questao": 68,
      "cor": "Vermelho",
      "resposta": "Ele escavou um túnel na montanha.",
    },
            { "questao": 69, "cor": "Verde", "resposta": "Sonic usa luvas brancas." },
            {
      "questao": 70,
      "cor": "Vermelho",
      "resposta": "Nosso amigo corre em alta velocidade.",
    },
            { "questao": 71, "cor": "Amarelo", "resposta": "Fogo e lava são muito quentes." },
            {
      "questao": 72,
      "cor": "Vermelho",
      "resposta": "Pedras vulcânicas voam para o alto.",
    },
            { "questao": 73, "cor": "Amarelo", "resposta": "gasolina" },
            { "questao": 74, "cor": "Amarelo", "resposta": "pés" },
            { "questao": 75, "cor": "Amarelo", "resposta": "eletricidade" },
            { "questao": 76, "cor": "Azul", "resposta": "vento" },
            { "questao": 77, "cor": "Amarelo", "resposta": "carvão" },
            { "questao": 78, "cor": "Vermelho", "resposta": "bateria" },
            { "questao": 79, "cor": "Verde", "resposta": "ar" },
            { "questao": 80, "cor": "Amarelo", "resposta": "pilha" },
            { "questao": 81, "cor": "Amarelo", "resposta": "Balão" },
            { "questao": 82, "cor": "Amarelo", "resposta": "Planador" },
            { "questao": 83, "cor": "Amarelo", "resposta": "14-Bis" },
            { "questao": 84, "cor": "Vermelho", "resposta": "Biplano" },
            { "questao": 85, "cor": "Azul", "resposta": "Caça" },
            { "questao": 86, "cor": "Amarelo", "resposta": "Ônibus espacial" },
            { "questao": 87, "cor": "Verde", "resposta": "derreteu" },
            { "questao": 88, "cor": "Azul", "resposta": "mar" },
            { "questao": 89, "cor": "Amarelo", "resposta": "Santos Dumont" },
            { "questao": 90, "cor": "Vermelho", "resposta": "asa-delta" },
        ],
        "programa_4": [
            { "questao": 91, "cor": "Verde", "resposta": "ar" },
            { "questao": 92, "cor": "Azul", "resposta": "em volta" },
            { "questao": 93, "cor": "Vermelho", "resposta": "esquentam" },
            { "questao": 94, "cor": "Verde", "resposta": "leve" },
            { "questao": 95, "cor": "Amarelo", "resposta": "sobe" },
            { "questao": 96, "cor": "Amarelo", "resposta": "desce" },
            { "questao": 97, "cor": "Verde", "resposta": "ventos" },
            { "questao": 98, "cor": "Azul", "resposta": "brisa" },
            { "questao": 99, "cor": "Vermelho", "resposta": "ventania" },
            { "questao": 100, "cor": "Vermelho", "resposta": "furacão" },
            { "questao": 101, "cor": "Verde", "resposta": "ciclone" },
            { "questao": 102, "cor": "Vermelho", "resposta": "Equador" },
            { "questao": 103, "cor": "Verde", "resposta": "som" },
            { "questao": 104, "cor": "Azul", "resposta": "antes" },
            { "questao": 105, "cor": "Amarelo", "resposta": "mais" },
            { "questao": 106, "cor": "Azul", "resposta": "supersônico" },
            { "questao": 107, "cor": "Azul", "resposta": "não" },
            { "questao": 108, "cor": "Verde", "resposta": "luz" },
            { "questao": 109, "cor": "Verde", "resposta": "Sol" },
            { "questao": 110, "cor": "Azul", "resposta": "365" },
            { "questao": 111, "cor": "Azul", "resposta": "clarão" },
            { "questao": 112, "cor": "Azul", "resposta": "barulho" },
            { "questao": 113, "cor": "Verde", "resposta": "elétrica" },
            { "questao": 114, "cor": "Vermelho", "resposta": "relâmpago" },
            { "questao": 115, "cor": "Vermelho", "resposta": "trovão" },
            { "questao": 116, "cor": "Azul", "resposta": "altos" },
            { "questao": 117, "cor": "Amarelo", "resposta": "A" },
            { "questao": 118, "cor": "Verde", "resposta": "B" },
            { "questao": 119, "cor": "Azul", "resposta": "C" },
            { "questao": 120, "cor": "Vermelho", "resposta": "D" },
        ],
        "programa_5": [
            { "questao": 121, "cor": "Verde", "resposta": "correr" },
            { "questao": 122, "cor": "Amarelo", "resposta": "nadar" },
            { "questao": 123, "cor": "Amarelo", "resposta": "águia" },
            { "questao": 124, "cor": "Verde", "resposta": "sapo" },
            { "questao": 125, "cor": "Vermelho", "resposta": "lambaris" },
            { "questao": 126, "cor": "Amarelo", "resposta": "mais" },
            { "questao": 127, "cor": "Azul", "resposta": "D" },
            { "questao": 128, "cor": "Vermelho", "resposta": "E" },
            { "questao": 129, "cor": "Verde", "resposta": "C" },
            { "questao": 130, "cor": "Vermelho", "resposta": "A" },
            { "questao": 131, "cor": "Azul", "resposta": "B" },
            { "questao": 132, "cor": "Vermelho", "resposta": "F" },
            { "questao": 133, "cor": "Amarelo", "resposta": "GIRA" },
            { "questao": 134, "cor": "Azul", "resposta": "MERGULHA" },
            { "questao": 135, "cor": "Azul", "resposta": "SALTAR" },
            { "questao": 136, "cor": "Azul", "resposta": "CORRER" },
            { "questao": 137, "cor": "Verde", "resposta": "ATACAR" },
            { "questao": 138, "cor": "Azul", "resposta": "VOAR" },
            { "questao": 139, "cor": "Vermelho", "resposta": "A" },
            { "questao": 140, "cor": "Amarelo", "resposta": "B" },
            { "questao": 141, "cor": "Azul", "resposta": "C" },
            { "questao": 142, "cor": "Verde", "resposta": "D" },
            { "questao": 143, "cor": "Vermelho", "resposta": "E" },
            { "questao": 144, "cor": "Amarelo", "resposta": "F" },
            { "questao": 145, "cor": "Azul", "resposta": "G" },
            { "questao": 146, "cor": "Verde", "resposta": "H" },
            { "questao": 147, "cor": "Verde", "resposta": "esquiando" },
            { "questao": 148, "cor": "Azul", "resposta": "mergulhando" },
            { "questao": 149, "cor": "Vermelho", "resposta": "gelo" },
            { "questao": 150, "cor": "Amarelo", "resposta": "montanha" },
        ],
    },
}
