name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: pip3 install --break-system-packages customtkinter==5.2.2 darkdetect typing_extensions pyinstaller

      - name: Compilar executável
        run: python3 -m PyInstaller --onefile --noconsole --name penseBem_${{ github.ref_name }} main.py

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: dist/penseBem_${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
